#!/bin/bash

docker build -t dpflasterer/nordvpn-meshnet:latest -t dpflasterer/nordvpn-meshnet:$1 --platform=linux/amd64 . && docker push dpflasterer/nordvpn-meshnet:latest && docker push dpflasterer/nordvpn-meshnet:$1